### ISSUE TITLE
Size of column and row

### ISSUE THREAD

**Issue by abeq** [appleple/a-table.js#1]
I think It is better, if it is able to change width of column and height of row with adjust by drug or input size (into width attribute of col).

**Comment by steelydylan** [comment]
Hi abeq :)
Thank you for your advice
I'll add the feature someday, I think it's difficult to resize cells on border drag tho :(
If you have any ideas, plz let me know :D

**Comment by abeq** [comment]
Thank for your reply.
I think that it is good to set by entering a width.

I am looking forward to future development.
